### ISSUE TITLE
Demo not connecting

### ISSUE THREAD

**Issue by cplotter** [alfredbaudisch/GodotPhoenixChannels#22]
I am unable to get the demo to connect: `_on_Socket_error: {message:connection error}`

**Comment by alfredbaudisch** [comment]
That happens when it can't find the Elixir server. Did you run the Elixir demo project as well and correctly set the details into the demo GUI?

**Comment by cplotter** [comment]
@alfredbaudisch I made a silly mistake by not setting the `localhost` portion to `0.0.0.0`

Working fine now thanks!

I will be playing around with this :) I want to ditch webgl and elm and use godot instead since I want to focus more on making the game than building my own engine. 

Kind Regards
