### ISSUE TITLE
Publish to AssetLib

### ISSUE THREAD

**Issue by Comyune** [alfredbaudisch/GodotPhoenixChannels#25]
What do you think is required before this can be published to the Godot AssetLib?

I'm happy to help if you'd like someone to add unit tests to what is already there perhaps... or additional testing & docs!

**Comment by alfredbaudisch** [comment]
Thank you, as soon as I finish Godello, I'll work on this. If you already have something to contribute, please feel free to add PRs :) Any help is welcome!

**Comment by mstefanini** [comment]
The #30 can be a move forward to an official release on AssetsLib.

However, deploying it is another story. I don't know if there is an API to deploy it automatically.
Seeing the doc, I don't think so.

**Comment by alfredbaudisch** [comment]
This addon is now published in the AssetLib for both Godot 3 and Godot 4 (two separate libs), see the updated README. Also the demo project has been moved out to another repository. Instructions also in the readme.

Thanks @mstefanini for the initial push!
